### ISSUE TITLE
Lingua del sito

### ISSUE THREAD

**Issue by whiteseraph83** [italia/design-comuni-drupal-theme#17]
Abbiamo notato che una volta completata la procedura di installazione del tema e caricate le configurazioni (`drush cim`) la lingua di default del sito viene settata in inglese.
Quando la modifichiamo in Italiano, i contenuti ed i termini di tassonomia non sono più raggiungibili perchè in fase di importazione (Content Syncronizer) dei 4 bundle, ogni entità ha impostato come langcode "en".

Inoltre quando riaggiorniamo il tema all'ultima versione e rieseguiamo il `drush cim`  la lingua del sito viene reimpostata in inglese.

Ad esempio il file (importato durante l'istruzione `drush cim`):
/design-comuni-drupal-theme/comuni_theme/config/sync/system.site.yml
contiene le seguenti definizioni:
```
_core:
  default_config_hash: 94d95421-24ae-4514-bfd3-7b52524a23cd
langcode: en
uuid: 94d95421-24ae-4514-bfd3-7b52524a23cd
name: 'Nome del comune'
mail: v2comunidrupalct@example.com
slogan: 'Slogan del comune'
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
```

Come si può notare, la lingua del sito (`default_langcode`) viene impostata di default in Inglese.

Suggeriamo di impostare il sito in italiano come lingua di default prima di effettuare il drush cex e rivedere i bundle sempre per impostarli in lingua italiana.

Grazie
